# Generated by Django 5.1.15 on 2026-06-23 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagemedia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagemedia',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='event.message'),
        ),
        migrations.AddField(
            model_name='occasion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occasion',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occasions', to='event.eventtype'),
        ),
        migrations.AddField(
            model_name='occasion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='event.occasion'),
        ),
        migrations.AddField(
            model_name='occasiongallery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occasiongallery',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='event.occasion'),
        ),
        migrations.AddIndex(
            model_name='occasion',
            index=models.Index(fields=['owner', 'status'], name='event_occas_owner_i_5dbae1_idx'),
        ),
        migrations.AddIndex(
            model_name='occasion',
            index=models.Index(fields=['event_type', 'slug'], name='event_occas_event_t_19871b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['occasion'], name='event_messa_occasio_968470_idx'),
        ),
    ]
