# Generated by Django 5.1.15 on 2026-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_occasion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasiongallery',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
