# Generated by Django 6.0.4 on 2026-06-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_occasiongallery_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='When True the message is hidden from the public wall but not deleted.'),
        ),
    ]
