# Generated by Django 5.1.15 on 2026-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_audio',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_images',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_audio_count',
            field=models.PositiveIntegerField(default=0, help_text='Max audio uploads per occasion.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_images_count',
            field=models.PositiveIntegerField(default=50, help_text='Max images per occasion.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_video_count',
            field=models.PositiveIntegerField(default=0, help_text='Max videos per occasion.'),
        ),
    ]
