# Generated by Django 5.1.15 on 2026-06-23 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscriptionplan_max_audio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSubscriptionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('max_images_count', models.PositiveIntegerField(default=1000, help_text='Max images per occasion.')),
                ('max_video_count', models.PositiveIntegerField(default=100, help_text='Max videos per occasion.')),
                ('max_audio_count', models.PositiveIntegerField(default=100, help_text='Max audio uploads per occasion.')),
                ('max_storage', models.PositiveIntegerField(default=10000, help_text='Total storage allowance in MB.')),
                ('allow_video', models.BooleanField(default=True)),
                ('allow_audio_message', models.BooleanField(default=True)),
                ('max_video_size', models.PositiveIntegerField(default=500, help_text='Max size per video upload, in MB.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Subscription Config',
                'verbose_name_plural': 'Admin Subscription Config',
            },
        ),
    ]
