# Generated by Django 5.1.15 on 2026-06-23 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_adminsubscriptionconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Only one plan can be the free plan.'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_free', True)), fields=('is_free',), name='unique_free_plan'),
        ),
    ]
