# Generated by Django 5.1.15 on 2026-06-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionplan_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsubscriptionconfig',
            name='max_gallery_images',
            field=models.PositiveIntegerField(default=5, help_text='Max gallery images an owner can attach to an occasion (platform-wide).'),
        ),
    ]
