# Generated by Django 5.1.15 on 2026-06-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_adminsubscriptionconfig_max_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsubscriptionconfig',
            name='max_video_size',
        ),
        migrations.AddField(
            model_name='adminsubscriptionconfig',
            name='max_audio_per_message',
            field=models.PositiveIntegerField(default=1, help_text='Max audio files a guest can attach to one message.'),
        ),
        migrations.AddField(
            model_name='adminsubscriptionconfig',
            name='max_images_per_message',
            field=models.PositiveIntegerField(default=5, help_text='Max images a guest can attach to one message.'),
        ),
        migrations.AddField(
            model_name='adminsubscriptionconfig',
            name='max_upload_audio_size_mb',
            field=models.PositiveIntegerField(default=10, help_text='Global max size per audio upload, in MB.'),
        ),
        migrations.AddField(
            model_name='adminsubscriptionconfig',
            name='max_upload_image_size_mb',
            field=models.PositiveIntegerField(default=5, help_text='Global max size per image upload, in MB.'),
        ),
        migrations.AddField(
            model_name='adminsubscriptionconfig',
            name='max_upload_video_size_mb',
            field=models.PositiveIntegerField(default=50, help_text='Global max size per video upload, in MB.'),
        ),
        migrations.AddField(
            model_name='adminsubscriptionconfig',
            name='max_videos_per_message',
            field=models.PositiveIntegerField(default=1, help_text='Max videos a guest can attach to one message.'),
        ),
    ]
