# Generated by Django 5.1.15 on 2026-06-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_passwordchangeotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='media_storage_used_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
