# Generated by Django 5.1.15 on 2026-06-24 01:00

from django.db import migrations
from django.db.models import Sum

def populate_storage_used(apps, schema_editor):
    User = apps.get_model('user', 'User')
    MessageMedia = apps.get_model('event', 'MessageMedia')
    OccasionGallery = apps.get_model('event', 'OccasionGallery')

    for user in User.objects.all():
        messages_bytes = MessageMedia.objects.filter(message__occasion__owner=user).aggregate(total=Sum('file_size'))['total'] or 0
        gallery_bytes = OccasionGallery.objects.filter(occasion__owner=user).aggregate(total=Sum('file_size'))['total'] or 0
        total_bytes = messages_bytes + gallery_bytes

        if total_bytes > 0:
            user.media_storage_used_bytes = total_bytes
            user.save(update_fields=['media_storage_used_bytes'])

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_media_storage_used_bytes'),
        ('event', '0004_occasiongallery_file_size'),
    ]

    operations = [
        migrations.RunPython(populate_storage_used, reverse_code=migrations.RunPython.noop),
    ]
